print('Hello World')
print('Smrdis')
print('VPN sucks')
print('json')
print('handle webhook')
print('exception')
print('neco')
print('something')
print('PR')
print('PR master')
print('PR main')
print('code owner')
print('push')
print('branch')
